var countryToContinent = {
    "Antigua and Barbuda": "n-america",
    "Bahamas": "n-america",
    "Barbados": "n-america",
    "Belize": "n-america",
    "Canada": "n-america",
    "Costa Rica": "n-america",
    "Cuba": "n-america",
    "Dominica": "n-america",
    "Dominican Republic": "n-america",
    "El Salvador": "n-america",
    "Grenada": "n-america",
    "Guatemala": "n-america",
    "Haiti": "n-america",
    "Honduras": "n-america",
    "Jamaica": "n-america",
    "Mexico": "n-america",
    "Nicaragua": "n-america",
    "Panama": "n-america",
    "Saint Kitts and Nevis": "n-america",
    "Saint Vincent and the Grenadines": "n-america",
    "Trinidad and Tobago": "n-america",
    "United States of America": "n-america",
    "Anguilla (UK)": "n-america",
    "Aruba (Netherlands)": "n-america",
    "Bermuda (UK)": "n-america",
    "Bonaire (Netherlands)": "n-america",
    "British Virgin Islands (UK)": "n-america",
    "Cayman Islands (UK)": "n-america",
    "Clipperton Island (France)": "n-america",
    "Curaçao (Netherlands)": "n-america",
    "Greenland (Denmark)": "n-america",
    "Guadeloupe (France)": "n-america",
    "Martinique (France)": "n-america",
    "Montserrat (UK)": "n-america",
    "Navassa Island (USA)": "n-america",
    "Puerto Rico (USA)": "n-america",
    "Saba (Netherlands)": "n-america",
    "Saint Barthélemy (France)": "n-america",
    "Saint Martin (France)": "n-america",
    "Saint Pierre and Miquelon (France)": "n-america",
    "Sint Eustatius (Netherlands)": "n-america",
    "Sint Maarten (Netherlands)": "n-america",
    "Turks and Caicos (UK)": "n-america",
    "US Virgin Islands (USA)": "n-america",
    "Algeria": "africa",
    "Angola": "africa",
    "Benin": "africa",
    "Botswana": "africa",
    "Burkina Faso": "africa",
    "Burundi": "africa",
    "Cabo Verde/Cape Verde": "africa",
    "Cameroon": "africa",
    "Central African Republic": "africa",
    "Chad": "africa",
    "Comoros": "africa",
    "Congo/Republic of the Congo": "africa",
    "Democratic Republic of the Congo": "africa",
    "Djibouti": "africa",
    "Egypt (transcontinental)": "africa",
    "Equatorial Guinea": "africa",
    "Eritrea": "africa",
    "Eswatini (formerly Swaziland)": "africa",
    "Ethiopia": "africa",
    "Gabon": "africa",
    "Gambia": "africa",
    "Ghana": "africa",
    "Guinea": "africa",
    "Guinea-Bissau": "africa",
    "Ivory Coast/Republic of Côte d'Ivoire": "africa",
    "Kenya": "africa",
    "Lesotho": "africa",
    "Liberia": "africa",
    "Libya": "africa",
    "Madagascar": "africa",
    "Malawi": "africa",
    "Mali": "africa",
    "Mauritania": "africa",
    "Mauritius": "africa",
    "Morocco": "africa",
    "Mozambique": "africa",
    "Namibia": "africa",
    "Niger": "africa",
    "Nigeria": "africa",
    "Rwanda": "africa",
    "Sao Tome and Principe": "africa",
    "Senegal": "africa",
    "Seychelles": "africa",
    "Sierra Leone": "africa",
    "Somalia": "africa",
    "South Africa": "africa",
    "South Sudan": "africa",
    "Sudan": "africa",
    "Tanzania": "africa",
    "Togo": "africa",
    "Tunisia": "africa",
    "Uganda": "africa",
    "Zambia": "africa",
    "Zimbabwe": "africa",
    "Canary Islands (Spain)": "africa",
    "Ceuta (Spain)": "africa",
    "French Southern and Antarctic Lands (France)": "africa",
    "Madeira (Portugal)": "africa",
    "Mayotte (France)": "africa",
    "Melilla (Spain)": "africa",
    "Pelagie Islands (Italy)": "africa",
    "Plazas de Soberania (Spain)": "africa",
    "Reunion (France)": "africa",
    "Saint Helena, Ascension and Tristan da Cunha (UK)": "africa",
    "Socotra Archipelago (Yemen)": "africa",
    "Afghanistan": "asia",
    "Armenia (transcontinental)": "asia",
    "Azerbaijan (transcontinental)": "asia",
    "Bahrain": "asia",
    "Bangladesh": "asia",
    "Bhutan": "asia",
    "British Indian Ocean Territory (UK territory)": "asia",
    "Brunei": "asia",
    "Cambodia": "asia",
    "China": "asia",
    "Cyprus (transcontinental)": "asia",
    "Egypt (transcontinental)": "asia",
    "Georgia (transcontinental)": "asia",
    "Hong Kong (China - Special Administrative Region)": "asia",
    "India": "asia",
    "Indonesia": "asia",
    "Iran": "asia",
    "Iraq": "asia",
    "Israel (U.N. member, though partially unrecognized)": "asia",
    "Japan": "asia",
    "Jordan": "asia",
    "Kazakhstan (transcontinental)": "asia",
    "Kuwait": "asia",
    "Kyrgyzstan": "asia",
    "Laos": "asia",
    "Lebanon": "asia",
    "Macau (China - Special Administrative Region)": "asia",
    "Malaysia": "asia",
    "Maldives": "asia",
    "Mongolia": "asia",
    "Myanmar (formerly Burma)": "asia",
    "Nepal": "asia",
    "North Korea (Democratic People's Republic of Korea)": "asia",
    "Oman": "asia",
    "Pakistan": "asia",
    "Palestine (limited recognition)": "asia",
    "Philippines": "asia",
    "Qatar": "asia",
    "Russia (transcontinental)": "asia",
    "Saudi Arabia": "asia",
    "Singapore": "asia",
    "South Korea (Republic of Korea)": "asia",
    "Sri Lanka": "asia",
    "Syria": "asia",
    "Taiwan (limited recognition - claimed by China)": "asia",
    "Tajikistan": "asia",
    "Thailand": "asia",
    "Timor-Leste/East Timor": "asia",
    "Turkey (transcontinental)": "asia",
    "Turkmenistan": "asia",
    "United Arab Emirates": "asia",
    "Uzbekistan": "asia",
    "Vietnam": "asia",
    "Yemen": "asia",
    "Albania": "europe",
    "Andorra": "europe",
    "Armenia (transcontinental)": "europe",
    "Austria": "europe",
    "Azerbaijan (transcontinental)": "europe",
    "Belarus": "europe",
    "Belgium": "europe",
    "Bosnia and Herzegovina": "europe",
    "Bulgaria": "europe",
    "Croatia": "europe",
    "Cyprus (generally considered European)": "europe",
    "Czechia/Czech Republic": "europe",
    "Denmark": "europe",
    "Estonia": "europe",
    "Finland": "europe",
    "France": "europe",
    "Georgia (transcontinental)": "europe",
    "Germany": "europe",
    "Greece": "europe",
    "Hungary": "europe",
    "Iceland": "europe",
    "Ireland": "europe",
    "Italy": "europe",
    "Kazakhstan (transcontinental)": "europe",
    "Latvia": "europe",
    "Liechtenstein": "europe",
    "Lithuania": "europe",
    "Luxembourg": "europe",
    "Malta": "europe",
    "Moldova": "europe",
    "Monaco": "europe",
    "Montenegro": "europe",
    "Netherlands": "europe",
    "North Macedonia": "europe",
    "Norway": "europe",
    "Poland": "europe",
    "Portugal": "europe",
    "Romania": "europe",
    "Russia (transcontinental)": "europe",
    "San Marino": "europe",
    "Serbia": "europe",
    "Slovakia": "europe",
    "Slovenia": "europe",
    "Spain": "europe",
    "Sweden": "europe",
    "Switzerland": "europe",
    "Turkey (transcontinental)": "europe",
    "Ukraine": "europe",
    "United Kingdom": "europe",
    "Vatican City (Holy See)": "europe",
    "Åland (Finland)": "europe",
    "Channel Islands (UK)": "europe",
    "Faroe Islands (Denmark)": "europe",
    "Gibraltar (UK)": "europe",
    "Guernsey (UK - crown dependency)": "europe",
    "Isle of Man (UK - crown dependency)": "europe",
    "Jersey (UK - crown dependency)": "europe",
    "Northern Cyprus (not recognized, claimed by Cyprus)": "europe",
    "Northern Ireland (UK)": "europe",
    "Svalbard (Norway)": "europe",
    "Australia": "australia",
    "Fiji": "australia",
    "Kiribati": "australia",
    "Marshall Islands": "australia",
    "Micronesia (The Federated States of)": "australia",
    "Nauru": "australia",
    "New Zealand": "australia",
    "Palau": "australia",
    "Papua New Guinea": "australia",
    "Samoa": "australia",
    "Solomon Islands": "australia",
    "Tonga": "australia",
    "Tuvalu": "australia",
    "Vanuatu": "australia",
    "American Samoa (US)": "australia",
    "Ashmore and Cartier Islands (Australia)": "australia",
    "Baker Island (US)": "australia",
    "Cook Islands (New Zealand)": "australia",
    "Coral Sea Islands (Australia)": "australia",
    "Easter Island (Chile)": "australia",
    "French Polynesia (France)": "australia",
    "Galapagos Islands (Ecuador)": "australia",
    "Guam (US)": "australia",
    "Howland Island (US)": "australia",
    "Jarvis Island (US)": "australia",
    "Johnston Atoll (US)": "australia",
    "Kingman Reef (US)": "australia",
    "Midway Atoll (US)": "australia",
    "New Caledonia (France)": "australia",
    "Niue (New Zealand)": "australia",
    "Norfolk Island (Australia)": "australia",
    "Northern Mariana Islands (US)": "australia",
    "Palmyra Atoll (US)": "australia",
    "Papua (Indonesia)": "australia",
    "Pitcairn Islands (UK)": "australia",
    "San Andrés and Providencia (Colombia)": "australia",
    "Tokelau (New Zealand)": "australia",
    "Wake Island (US)": "australia",
    "Wallis and Futuna (France)": "australia",
    "West Papua (Indonesia)": "australia",
    "Argentina": "s-america",
    "Brazil": "s-america",
    "Chile": "s-america",
    "Colombia": "s-america",
    "Ecuador": "s-america",
    "Guyana": "s-america",
    "Paraguay": "s-america",
    "Peru": "s-america",
    "Suriname": "s-america",
    "Uruguay": "s-america",
    "Venezuela": "s-america",
    "Bouvet Island (Norway)": "s-america",
    "Falkland Islands (UK)": "s-america",
    "French Guinea (France)": "s-america",
    "Nueva Esparta (Venezuela)": "s-america",
    "South Georgia and the South Sandwich Islands (UK)": "s-america",

};

var countries = Object.keys(countryToContinent);

function getRandomCountry() {
    const randomIndex = Math.floor(Math.random() * countries.length);
    const randomCountry = countries[randomIndex];
    return randomCountry;
}

document.getElementById('run').addEventListener('click', function () {
    const randomCountry = getRandomCountry();
    const correctContinent = countryToContinent[randomCountry];


    document.querySelector('.country input').value = randomCountry;


    var continents = document.querySelectorAll('.world-map div');
    continents.forEach(function (continentDiv) {
        continentDiv.addEventListener('click', function () {
            if (continentDiv.id === correctContinent) {
                alert("Correct! The country belongs to " + continentDiv.id);
            } else {
                alert("Incorrect. The country does not belong to " + continentDiv.id);
            }
        });
    });
});